# Generated by Django 3.2.5 on 2021-10-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='user',
            new_name='customuser',
        ),
    ]
